events{} # default die ingesteld staan zijn voldoende

http {
    
    include /etc/nginx/mime.types; 
    server {
       
        listen 80; #80 is default poort voor http
        
        server_name localhost; #inorde want draait op docker (dus via localhost)
        
        root /usr/share/nginx/html; # path naar ..
        
        index index.html; # naam van index html
        location / {
            
            try_files $uri $uri/ /index.html; # moeilijk - Deze regel probeert de inkomende request te verwerken als static files. Hiervoor zoekt hij eerste naar de specifieke file, dan naar de directory en tenslotte een fallback naar de index file. Dit laatste is cruciaal voor SPA's.
        }
    }
}
